package com.certguard.controller;

import com.certguard.client.RenewalServiceClient;
import com.certguard.dto.request.AgentCsrSubmitRequest;
import com.certguard.dto.request.AgentJobReportRequest;
import com.certguard.dto.request.AgentNetworkResultsBatch;
import com.certguard.dto.request.AgentScanResultRequest;
import com.certguard.dto.response.AgentResponse;
import com.certguard.dto.response.DeliveryJobResponse;
import com.certguard.dto.response.RegistrationTokenResponse;
import com.certguard.dto.response.ScanJobResponse;
import com.certguard.entity.Agent;
import com.certguard.entity.AgentJob;
import com.certguard.exception.ResourceNotFoundException;
import com.certguard.repository.AgentJobRepository;
import com.certguard.security.CertGuardUserPrincipal;
import com.certguard.security.TenantContext;
import com.certguard.service.AgentJobService;
import com.certguard.service.AgentService;
import com.certguard.service.NetworkScanService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping(value = "/api/v1/agent", produces = "application/json")
@RequiredArgsConstructor
public class AgentController {

    private final AgentService agentService;
    private final AgentJobService agentJobService;
    private final AgentJobRepository agentJobRepository;
    private final RenewalServiceClient renewalServiceClient;
    private final NetworkScanService networkScanService;

    // ── Admin endpoints (JWT auth) ─────────────────────────────

    @PostMapping("/tokens")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','PLATFORM_ADMIN')")
    public ResponseEntity<RegistrationTokenResponse> generateToken(
            @RequestParam @jakarta.validation.constraints.Pattern(
                regexp = "^[A-Za-z0-9 _.-]{3,64}$",
                message = "agentName must be 3–64 characters: letters, digits, spaces, hyphens, dots, underscores")
            String agentName,
            @AuthenticationPrincipal CertGuardUserPrincipal principal) {

        RegistrationTokenResponse resp = agentService.generateRegistrationToken(
                TenantContext.getOrgId(), agentName, principal.getUserId());
        return ResponseEntity.status(HttpStatus.CREATED).body(resp);
    }

    @GetMapping("/config")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','PLATFORM_ADMIN')")
    public ResponseEntity<String> downloadConfig(
            @RequestParam String agentName,
            @RequestParam String token,
            HttpServletRequest httpRequest) {

        UUID orgId = TenantContext.getOrgId();
        String serverUrl = httpRequest.getScheme() + "://"
                + httpRequest.getServerName() + ":" + httpRequest.getServerPort();

        String config = """
                # CertGuard Agent Configuration
                # Generated by CertGuard Cloud portal
                # Deploy this file alongside certguard-agent.jar

                # Server connection
                certguard.server.url=%s
                certguard.server.trust-self-signed=true

                # Registration (auto-cleared after first run)
                certguard.registration.token=%s
                certguard.registration.org-id=%s

                # Agent identity (auto-filled after registration)
                certguard.agent.id=
                certguard.agent.key=
                certguard.agent.name=%s

                # Network scope — edit to match your private network ranges
                certguard.agent.allowed-cidrs=192.168.0.0/16,10.0.0.0/8

                # Scan settings
                certguard.agent.max-targets=50
                certguard.agent.poll-interval-seconds=30
                certguard.agent.scan-timeout-seconds=10
                certguard.agent.scan-threads=5
                """.formatted(serverUrl, token, orgId, agentName);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=\"application.properties\"")
                .contentType(MediaType.TEXT_PLAIN)
                .body(config);
    }

    @GetMapping("/list")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','VIEWER','PLATFORM_ADMIN')")
    public ResponseEntity<List<AgentResponse>> listAgents() {
        return ResponseEntity.ok(agentService.listAgents(TenantContext.getOrgId()));
    }

    @PostMapping("/{agentId}/revoke")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','PLATFORM_ADMIN')")
    public ResponseEntity<Void> revokeAgent(@PathVariable UUID agentId) {
        agentService.revokeAgent(agentId, TenantContext.getOrgId());
        return ResponseEntity.noContent().build();
    }

    // ── Public endpoints ───────────────────────────────────────

    @PostMapping("/register")
    public ResponseEntity<?> register(
            @Valid @RequestBody com.certguard.dto.request.AgentRegisterRequest request,
            @RequestHeader("X-Org-Id") String orgIdStr) throws Exception {

        UUID orgId;
        try { orgId = UUID.fromString(orgIdStr); }
        catch (IllegalArgumentException e) {
            ProblemDetail pd = ProblemDetail.forStatusAndDetail(
                    HttpStatus.BAD_REQUEST, "Invalid or missing X-Org-Id header");
            return ResponseEntity.badRequest().body(pd);
        }

        AgentResponse resp = agentService.register(request, orgId);
        return ResponseEntity.status(HttpStatus.CREATED).body(resp);
    }

    // ── Agent endpoints (X-Agent-Key auth) ────────────────────

    @PostMapping("/heartbeat")
    public ResponseEntity<Map<String, Object>> heartbeat(HttpServletRequest request) {
        Agent agent = (Agent) request.getAttribute("authenticatedAgent");
        agentService.heartbeat(agent);
        return ResponseEntity.ok(Map.of(
                "status",     "ok",
                "agentId",    agent.getId(),
                "serverTime", java.time.Instant.now().toString()
        ));
    }

    @GetMapping("/jobs")
    public ResponseEntity<List<ScanJobResponse>> pollJobs(HttpServletRequest request) {
        Agent agent = (Agent) request.getAttribute("authenticatedAgent");
        return ResponseEntity.ok(agentService.pollJobs(agent));
    }

    @PostMapping("/results")
    public ResponseEntity<Void> submitResult(
            @Valid @RequestBody AgentScanResultRequest resultRequest,
            HttpServletRequest request) {

        Agent agent     = (Agent) request.getAttribute("authenticatedAgent");
        String agentKey = (String) request.getAttribute("authenticatedAgentKey");
        agentService.submitResult(agent, resultRequest, agentKey);
        return ResponseEntity.ok().build();
    }

    // ── RFC 0011: Network scan batch results ─────────────────────────────────

    /**
     * POST /api/v1/agent/network-results
     * Agent submits a batch of host/port scan results for a network sweep.
     * Guarded by AgentAuthFilter (X-Agent-Key authentication).
     * HMAC over "{networkScanId}:{chunkIndex}:{hostCount}:{timestamp}".
     */
    @PostMapping("/network-results")
    public ResponseEntity<Map<String, Object>> submitNetworkResults(
            @RequestBody @Valid AgentNetworkResultsBatch batch,
            HttpServletRequest request) {

        Agent agent     = (Agent) request.getAttribute("authenticatedAgent");
        String agentKey = (String) request.getAttribute("authenticatedAgentKey");
        networkScanService.ingestBatchResults(batch, agent, agentKey);

        boolean isComplete = batch.chunkIndex() == batch.totalChunks() - 1;
        return ResponseEntity.accepted().body(Map.of(
                "accepted",      batch.hosts().size(),
                "networkScanId", batch.networkScanId(),
                "status",        isComplete ? "COMPLETE" : "IN_PROGRESS"
        ));
    }

    // ── RFC 0004: Certificate renewal/delivery endpoints ────

    /**
     * GET /api/v1/agent/delivery-jobs
     * Claims and returns pending CERT_DELIVERY jobs for this agent.
     */
    @GetMapping("/delivery-jobs")
    public ResponseEntity<List<DeliveryJobResponse>> pollDeliveryJobs(HttpServletRequest request) {
        Agent agent = (Agent) request.getAttribute("authenticatedAgent");
        return ResponseEntity.ok(agentJobService.claimDeliveryJobs(agent));
    }

    /**
     * POST /api/v1/agent/jobs/{jobId}/csr
     * Agent submits the locally-generated CSR PEM. Private key stays on the agent host.
     * Core validates ownership, marks the CSR job complete, and forwards to renewal service.
     */
    @PostMapping("/jobs/{jobId}/csr")
    public ResponseEntity<Void> submitCsr(
            @PathVariable UUID jobId,
            @Valid @RequestBody AgentCsrSubmitRequest req,
            HttpServletRequest request) {

        Agent agent = (Agent) request.getAttribute("authenticatedAgent");

        AgentJob job = agentJobRepository.findByIdAndAgentId(jobId, agent.getId())
                .orElseThrow(() -> new ResourceNotFoundException("Job not found for this agent: " + jobId));

        if (job.getRenewalId() == null) {
            throw new ResourceNotFoundException("No renewal associated with CSR job: " + jobId);
        }

        // Forward CSR to renewal service (drives async CA flow)
        renewalServiceClient.submitCsr(job.getRenewalId(), req.csrPem());

        // Mark agent job complete
        agentJobService.completeJob(jobId, agent, AgentJobReportRequest.success());

        log.info("CSR submitted for jobId: {}, renewalId: {}", jobId, job.getRenewalId());
        return ResponseEntity.ok().build();
    }

    /**
     * GET /api/v1/agent/jobs/{jobId}/package
     * Streams the certificate package bytes. Proxied from renewal service.
     */
    @GetMapping("/jobs/{jobId}/package")
    public void downloadJobPackage(
            @PathVariable UUID jobId,
            HttpServletRequest request,
            HttpServletResponse response) throws IOException {

        Agent agent = (Agent) request.getAttribute("authenticatedAgent");

        AgentJob job = agentJobRepository.findByIdAndAgentId(jobId, agent.getId())
                .orElseThrow(() -> new ResourceNotFoundException("Job not found for this agent: " + jobId));

        if (job.getRenewalId() == null) {
            throw new ResourceNotFoundException("No renewal associated with job: " + jobId);
        }

        response.setContentType("application/x-pem-file");

        try (InputStream stream = renewalServiceClient.streamPackage(job.getRenewalId())) {
            stream.transferTo(response.getOutputStream());
        }
        log.info("Package streamed to agent for jobId: {}, renewalId: {}", jobId, job.getRenewalId());
    }

    /**
     * POST /api/v1/agent/jobs/{jobId}/report
     * Agent reports job completion or failure.
     */
    @PostMapping("/jobs/{jobId}/report")
    public ResponseEntity<Void> reportJob(
            @PathVariable UUID jobId,
            @RequestBody AgentJobReportRequest rep,
            HttpServletRequest request) {

        Agent agent = (Agent) request.getAttribute("authenticatedAgent");
        if ("FAILED".equalsIgnoreCase(rep.status())) {
            agentJobService.failJob(jobId, agent, rep);
        } else {
            agentJobService.completeJob(jobId, agent, rep);
        }
        return ResponseEntity.ok().build();
    }
}
