package com.certguard.controller;

import com.certguard.dto.request.AgentScanResultRequest;
import com.certguard.dto.response.AgentResponse;
import com.certguard.dto.response.RegistrationTokenResponse;
import com.certguard.dto.response.ScanJobResponse;
import com.certguard.entity.Agent;
import com.certguard.security.CertGuardUserPrincipal;
import com.certguard.security.TenantContext;
import com.certguard.service.AgentService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping(value = "/api/v1/agent", produces = "application/json")
public class AgentController {

    private final AgentService agentService;

    public AgentController(AgentService agentService) {
        this.agentService = agentService;
    }

    // ── Admin endpoints (JWT auth) ─────────────────────────────
    // NOTE: POST /api/v1/agents (create + bundle) and GET /api/v1/agents/{id}/bundle
    // are served by AgentProvisionController — they were removed from here because
    // the absolute paths in @PostMapping/@GetMapping values were being concatenated
    // with this class's /api/v1/agent prefix, producing broken routes.

    /**
     * POST /api/v1/agent/tokens — generates a standalone registration token.
     * Requires ADMIN or PLATFORM_ADMIN role (BACKEND_REVIEW P1-5).
     * agentName validated to prevent content injection (BACKEND_REVIEW P2-6).
     */
    @PostMapping("/tokens")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','PLATFORM_ADMIN')")
    public ResponseEntity<RegistrationTokenResponse> generateToken(
            @RequestParam @jakarta.validation.constraints.Pattern(
                regexp = "^[A-Za-z0-9 _.-]{3,64}$",
                message = "agentName must be 3–64 characters: letters, digits, spaces, hyphens, dots, underscores")
            String agentName,
            @AuthenticationPrincipal CertGuardUserPrincipal principal) {

        RegistrationTokenResponse resp = agentService.generateRegistrationToken(
                TenantContext.getOrgId(), agentName, principal.getUserId());
        return ResponseEntity.status(HttpStatus.CREATED).body(resp);
    }

    /**
     * Returns a pre-filled application.properties for the user to copy or download.
     * Requires the registration token to be passed so it can be embedded.
     */
    @GetMapping("/config")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','PLATFORM_ADMIN')")
    public ResponseEntity<String> downloadConfig(
            @RequestParam String agentName,
            @RequestParam String token,
            HttpServletRequest httpRequest) {

        UUID orgId = TenantContext.getOrgId();
        String serverUrl = httpRequest.getScheme() + "://"
                + httpRequest.getServerName() + ":" + httpRequest.getServerPort();

        String config = """
                # CertGuard Agent Configuration
                # Generated by CertGuard Cloud portal
                # Deploy this file alongside certguard-agent.jar
                
                # Server connection
                certguard.server.url=%s
                certguard.server.trust-self-signed=true
                
                # Registration (auto-cleared after first run)
                certguard.registration.token=%s
                certguard.registration.org-id=%s
                
                # Agent identity (auto-filled after registration)
                certguard.agent.id=
                certguard.agent.key=
                certguard.agent.name=%s

                # Network scope — edit to match your private network ranges
                certguard.agent.allowed-cidrs=192.168.0.0/16,10.0.0.0/8
                
                # Scan settings
                certguard.agent.max-targets=50
                certguard.agent.poll-interval-seconds=30
                certguard.agent.scan-timeout-seconds=10
                certguard.agent.scan-threads=5
                """.formatted(serverUrl, token, orgId, agentName);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=\"application.properties\"")
                .contentType(MediaType.TEXT_PLAIN)
                .body(config);
    }

    @GetMapping("/list")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','VIEWER','PLATFORM_ADMIN')")
    public ResponseEntity<List<AgentResponse>> listAgents() {
        return ResponseEntity.ok(agentService.listAgents(TenantContext.getOrgId()));
    }

    @PostMapping("/{agentId}/revoke")
    @PreAuthorize("hasAnyRole('ADMIN','ENGINEER','PLATFORM_ADMIN')")
    public ResponseEntity<Void> revokeAgent(@PathVariable UUID agentId) {
        agentService.revokeAgent(agentId, TenantContext.getOrgId());
        return ResponseEntity.noContent().build();
    }

    // ── Public endpoints ───────────────────────────────────────

    @PostMapping("/register")
    public ResponseEntity<AgentResponse> register(
            @Valid @RequestBody com.certguard.dto.request.AgentRegisterRequest request,
            @RequestHeader("X-Org-Id") String orgIdStr) throws Exception {

        UUID orgId;
        try { orgId = UUID.fromString(orgIdStr); }
        catch (IllegalArgumentException e) { return ResponseEntity.badRequest().build(); }

        AgentResponse resp = agentService.register(request, orgId);
        return ResponseEntity.status(HttpStatus.CREATED).body(resp);
    }

    // ── Agent endpoints (X-Agent-Key auth) ────────────────────

    @PostMapping("/heartbeat")
    public ResponseEntity<Map<String, Object>> heartbeat(HttpServletRequest request) {
        Agent agent = (Agent) request.getAttribute("authenticatedAgent");
        agentService.heartbeat(agent);
        return ResponseEntity.ok(Map.of(
                "status",     "ok",
                "agentId",    agent.getId(),
                "serverTime", java.time.Instant.now().toString()
        ));
    }

    @GetMapping("/jobs")
    public ResponseEntity<List<ScanJobResponse>> pollJobs(HttpServletRequest request) {
        Agent agent = (Agent) request.getAttribute("authenticatedAgent");
        return ResponseEntity.ok(agentService.pollJobs(agent));
    }

    @PostMapping("/results")
    public ResponseEntity<Void> submitResult(
            @Valid @RequestBody AgentScanResultRequest resultRequest,
            HttpServletRequest request) {

        Agent agent     = (Agent) request.getAttribute("authenticatedAgent");
        String agentKey = (String) request.getAttribute("authenticatedAgentKey");
        agentService.submitResult(agent, resultRequest, agentKey);
        return ResponseEntity.ok().build();
    }
}
